### ISSUE TITLE
update GRB_fremi_swift to do VCS obs for Swift triggers

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/mwa_trigger#8]
Since short GRBs are more likely to be associated with BNS mergers, or FRB like signals, and since our swift triggers are more likely to be short GRBS, we should be triggering in VCS mode in order to have the best chance at capturing this emission.

**Comment by gemmaanderson** [comment]
I am not sure if this is working as we have had a few Swift triggers recently with "trigger_dur = 1.024s" but these only activated the standard correlator rather than the VCS (as far as I can tell from the log files as "vcsmode" is set to "false"). See the following event from 18 Dec 2019 (plus attached log files, etc - unfortunately, the VOEvent wont attach):
[clear_SWIFT_944916.txt](https://github.com/MWATelescope/mwa_trigger/files/4137277/clear_SWIFT_944916.txt)
[log_SWIFT_944916.txt](https://github.com/MWATelescope/mwa_trigger/files/4137278/log_SWIFT_944916.txt)
[schedule_SWIFT_944916.txt](https://github.com/MWATelescope/mwa_trigger/files/4137279/schedule_SWIFT_944916.txt)


> The GRB Fermi+Swift handler triggered an MWA observation for a
> Fermi/Swift GRB at 2019-12-18 02:43:04.146 UTC.
> 
> Details are:
> Trigger ID: SWIFT_944916
> RA:         20:04:18.624 hours
> Dec:        -40:16:26.4 deg
> Error Rad:    0.050 deg
> Result: SUCCESS - observation inserted into MWA schedule

**Comment by PaulHancock** [comment]
@gemmaanderson Github doesn't like .xml files for some reason. If you rename the voevent to have a .txt extension then you can upload it.

**Comment by gemmaanderson** [comment]
The VOEvent file has now been uploaded:
[voevent.txt](https://github.com/MWATelescope/mwa_trigger/files/4137684/voevent.txt)

**Comment by PaulHancock** [comment]
Cannot replicate ! Using the latest version of the software (19d740b) on my laptop with a python 2.7.14 environment, the voevent that you link sends a request that has `vcsmod:True`. This is the payload that is passed:

```
postdict={'freqres': 10, 'vcsmode': True, 'creator': 'VOEvent_Auto_Trigger_0.3', 'secure_key': '', 'pretend': True, 'calibrator': True, 'calexptime': 120, 'inttime': 0.5, 'nobs': 1, 'avoidsun': True, 'ra': 301.0776, 'freqspecs': '145,24', 'dec': -40.274, 'exptime': 30}
```
